[global.variables]
username = "zoickx"
full_name = "Ilia Zaichuk"
email = "zoickx@ztld.org"

[gui.variables]
mono_font_family = "Iosevka"
mono_font_size = "16.0"

[base16-theme.variables]
base16-theme-name = "base16-google-dark"
base00 = "#1d1f21"
base01 = "#282a2e"
base02 = "#373b41"
base03 = "#969896"
base04 = "#b4b7b4"
base05 = "#c5c8c6"
base06 = "#e0e0e0"
base07 = "#ffffff"
base08 = "#CC342B"
base09 = "#F96A38"
base0A = "#FBA922"
base0B = "#198844"
base0C = "#3971ED"
base0D = "#3971ED"
base0E = "#A36AC7"
base0F = "#3971ED"

#[base16-theme.variables]
#base16-theme-name = "base16-gruvbox-light-soft"
#base00 = "#f2e5bc"
#base01 = "#ebdbb2"
#base02 = "#d5c4a1"
#base03 = "#bdae93"
#base04 = "#665c54"
#base05 = "#504945"
#base06 = "#3c3836"
#base07 = "#282828"
#base08 = "#9d0006"
#base09 = "#af3a03"
#base0A = "#b57614"
#base0B = "#79740e"
#base0C = "#427b58"
#base0D = "#076678"
#base0E = "#8f3f71"
#base0F = "#d65d0e"

#[base16-theme.variables]
#base16-theme-name = "base16-dracula"
#base00 = "#282936"
#base01 = "#3a3c4e"
#base02 = "#4d4f68"
#base03 = "#626483"
#base04 = "#62d6e8"
#base05 = "#e9e9f4"
#base06 = "#f1f2f8"
#base07 = "#f7f7fb"
#base08 = "#ea51b2"
#base09 = "#b45bcf"
#base0A = "#00f769"
#base0B = "#ebff87"
#base0C = "#a1efe4"
#base0D = "#62d6e8"
#base0E = "#b45bcf"
#base0F = "#00f769"

[emacs]
depends = ["gui", "base16-theme"]

[emacs.files]
"emacs/early-init.el" = "~/.config/emacs/early-init.el"
"emacs/init.el"       = "~/.config/emacs/init.el"
"emacs/emacsd.org"    = "~/.config/emacs/emacsd.org"

[sway.files]
"sway/sway.conf" = "~/.config/sway/config"
"sway/waybar.conf" = "~/.config/waybar/config"
"sway/waybar.css" = "~/.config/waybar/style.css"
"sway/mako.conf" = "~/.config/mako/config"

[git]
depends = ["global"]

[git.files]
"git.conf" = "~/.config/git/config"

[zsh]
depends = ["base16-theme"]

[zsh.files]
"zsh/zshrc" = "~/.zshrc"
"zsh/zshenv" = "~/.zshenv"

[alacritty]
depends = ["gui", "base16-theme"]

[alacritty.files]
"alacritty.yml" = "~/.config/alacritty/alacritty.yml"

## Manually symlink directory: dotter symlinks files and I don't like that
#[aconfmgr.files]
#aconfmgr = "~/.config/aconfmgr"